addons:
  ssh_known_hosts:
    - liquality.io
rvm:
  - 2.3.1
branches:
  only:
    - master
cache: bundler
before_install:
  - openssl aes-256-cbc -K $encrypted_61c6cb899f1c_key -iv $encrypted_61c6cb899f1c_iv -in ./.travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - nvm install node
  - gem install bundler:1.16.6
  - bundle update
script:
  - bundle exec middleman build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    target-branch: gh-pages
    local-dir: "./build"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ $LIQUALITY_USER@$LIQUALITY_HOST:/var/www/html/io/liquality/
    on:
      branch: master
