rvm:
  - 2.3.1
branches:
  only:
    - master
cache: bundler
before_install:
  - nvm install node
script:
  - bundle exec middleman build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: gh-pages
  local-dir: ./build
  on:
    branch: master
